package ru.antisessa.enums;

public enum UserState {
    BASIC_STATE,
    FINDING_ONE_CAR,
    FINDING_ONE_CAR_FULL_INFO,

    FINDING_ONE_REFUEL,
    FINDING_ONE_REFUEL_FULL_INFO,
    CREATING_CAR_NAME,
    CREATING_CAR_ODOMETER,
    CREATING_CAR_GAS_TANK_VOLUME,
    CREATING_CAR_LAST_CONSUMPTION,
    CREATING_CAR_FINAL_VALIDATION,
    CREATING_REFUEL
}
